version: "3.9"

volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: waniakazmi
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://waniakazmi:my_password@postgres_db:5432/todo_db
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/code
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
      ]
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_URL: https://web.wania.xyz/api
    command: ["npm", "run", "dev"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_URL=http://backend:8001
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - backend
